import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 네비게이션 바 */}
        <nav className="bg-white-green px-20 fixed top-0 left-0 w-full z-50 opacity-90">
          
          <div className="flex justify-center block lg:hidden">
            <Link href="/">
              <Image src='/logo.png' alt="로고" width='80' height='20' className="py-3"></Image>
            </Link>
          </div>
          
          <div className="flex justify-evenly hidden lg:flex">
            <Link href="/">
              <Image src='/logo.png' alt="로고" width='80' height='20' className="py-3"></Image>
            </Link>
            <div className="flex justify-around"> 
              <Link href="/" className="mr-20 p-7 text-base text-deep-green font-bold transition-all hover:text-white duration-300">홈</Link>
              <Link href="/monitor" className="mr-20 p-7 text-base text-deep-green font-bold transition-all hover:text-white duration-300">모니터링</Link>
              <Link href="/analysis" className="mr-20 p-7 text-base text-deep-green font-bold transition-all hover:text-white duration-300">분석 및 통계</Link>
              <Link href="/setting" className="mr-20 p-7 text-base text-deep-green font-bold transition-all hover:text-white duration-300">설정</Link>
            </div>
            
          </div>
        </nav>
        
        {children}
      </body>
    </html>
  );
}
